### ISSUE TITLE
Support more models

### ISSUE THREAD

**Issue by kimond** [GroupeChemia/valexa#11]
Actually, we support only numpy's `polyfit` function up to 3 degrees. We would like to support more model such:

* weighted 1/x linear
* weighted quadratic
* sqrt(x) - sqrt(y)
* and more

We will need to refactor the model building.
 
I suggest an abstract class `BaseModel` with two methods `get_params` (retrieve formula's parameters by series) and `apply` (apply the formula to the validation data). Then, we will implement wanted models with classes such `LinearModel` with the corresponding behavior.

**NOTE:** We can still use `polyfit` inside the `get_params` method.

**Comment by HtheChemist** [comment]
I did a slight modification to the current existing code to adapt for this:
- Regression fitting is now done using the statsmodels library which gives a lot of info regarding the regression and support weight. I use statsmodels.formula.api.wls, which can manage weighted and non-weighted Least-Square fitting.
- Root finding is now done using sympy.solve
- Model:NAME_BY_DEGREE is now Model:EQUATION_BY_DEGREE and is a dict containing the following information:
-- name: Name of the model
-- formula: Formula of the model in Patsy format, this is used by statsmodels to fit the regression.
-- weight: This is a lambda function that return a matrix of the weight to apply. For non-weighted regression this return an array of ones.
-- function: This is a lambda function that return an expression that is use by sympu.solve to solve the equation. For Quadratic and other multiple root function I selected the min value. This may need to be changed eventually.

The list of supported model could probably be in a ModelBuilder class for more segragation. # #
